name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build project
        run: mvn clean package
        
      - name: SSH into remote server and stop application
        uses: appleboy/ssh-action@master
        with:
          host: apps.seriousbusiness.network
          username: ${{ secrets.REMOTE_USERNAME }}
          password: ${{ secrets.REMOTE_PASSWORD }}
          script: |
            sudo systemctl stop magic-shoppe

      - name: Copy artifact to remote server
        uses: appleboy/scp-action@master
        with:
          host: apps.seriousbusiness.network
          username: ${{ secrets.REMOTE_USERNAME }}
          password: ${{ secrets.REMOTE_PASSWORD }}
          source: target/spring-magic-shoppe.jar
          target: /path/on/remote/server/artifact.jar

      - name: SSH into remote server and start application
        uses: appleboy/ssh-action@master
        with:
          host: apps.seriousbusiness.network
          username: ${{ secrets.REMOTE_USERNAME }}
          password: ${{ secrets.REMOTE_PASSWORD }}
          script: |
            sudo systemctl start magic-shoppe
