name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      
      - name: Build Frontend
        run: |
          cd frontend
          npm ci
          npm run build
          cd ..

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build project
        run: mvn clean package
        
      - name: SSH into remote server and stop application
        uses: appleboy/ssh-action@master
        with:
          host: apps.seriousbusiness.network
          username: ${{ secrets.REMOTE_USERNAME }}
          password: ${{ secrets.REMOTE_PASSWORD }}
          script: |
            sudo systemctl stop magic-shoppe
            rm -rf /var/magic-shoppe/latest

      - name: Copy artifact to remote server
        uses: appleboy/scp-action@master
        with:
          host: apps.seriousbusiness.network
          username: ${{ secrets.REMOTE_USERNAME }}
          password: ${{ secrets.REMOTE_PASSWORD }}
          source: ${{ github.workspace }}/target/spring-magic-shoppe.jar
          target: /var/magic-shoppe/latest/spring-magic-shoppe.jar

      - name: SSH into remote server and start application
        uses: appleboy/ssh-action@master
        with:
          host: apps.seriousbusiness.network
          username: ${{ secrets.REMOTE_USERNAME }}
          password: ${{ secrets.REMOTE_PASSWORD }}
          script: |
            sudo systemctl start magic-shoppe
